# Generated by Django 3.2.3 on 2021-07-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
