# Generated by Django 3.2.3 on 2021-07-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudAPP', '0004_alter_webuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='webuser',
            name='timeStamp',
        ),
    ]
