# Generated by Django 3.2.3 on 2021-07-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudAPP', '0005_auto_20210730_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webadmin',
            name='fatherName',
        ),
    ]
