# Generated by Django 3.2.3 on 2021-07-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudAPP', '0006_remove_webadmin_fathername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webadmin',
            old_name='Email',
            new_name='Admin_Email',
        ),
        migrations.RenameField(
            model_name='webadmin',
            old_name='Password',
            new_name='Admin_Password',
        ),
        migrations.RenameField(
            model_name='webadmin',
            old_name='firstName',
            new_name='Admin_firstName',
        ),
        migrations.RenameField(
            model_name='webadmin',
            old_name='lastName',
            new_name='Admin_lastName',
        ),
        migrations.RenameField(
            model_name='webadmin',
            old_name='userName',
            new_name='Admin_userName',
        ),
    ]
