# Generated by Django 3.2.3 on 2021-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudAPP', '0007_auto_20210730_0306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebAdmin',
        ),
        migrations.AddField(
            model_name='webuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
