# Generated by Django 3.2.3 on 2021-08-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudAPP', '0009_deleteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webuser',
            name='id',
        ),
        migrations.AddField(
            model_name='webuser',
            name='key',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
