# Generated by Django 3.2.3 on 2021-08-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudAPP', '0011_auto_20210804_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='firstName',
            field=models.CharField(max_length=21),
        ),
    ]
